### ISSUE TITLE
Validate Incorrectly Throws Error When Embedded Field_Character Contains <CR><LF>

### ISSUE THREAD

**Issue by radiosci** [NASA-PDS/validate#325] opened 2021-04-09 19:34 UTC
## 🐛 Describe the bug
I have Table_Character files with long records.  Carriage-Return Line-Feed pairs have been embedded within the records to facilitate display; but the original (long) record length has been retained in the label.  Validate finds the embedded delimiter pairs, claims my records are too short, and throws errors.  
A prohibition on embedded Line-Feed and Carriage-Return characters was approved for Field_Delimited in CCB-181; a broader prohibition on non-printing control characters in Field_Character was proposed in CCB-196, but it was rejected by DDWG.  That presumably means Carriage-Return Line-Feed pairs may appear in embedded Field_Character so long as the records are correctly delimited by Carriage-Return Line-Feed.
Validate should return errors if character records are incorrectly delimited; it should not return errors if delimiter pairs are found internal to records.

## 📜 To Reproduce
1. Run validate on the attached crs009x.{tab, xml} product
2. See error report (crs009x_report.txt)

## 🕵️ Expected behavior
crs009x.{tab, xml} should pass.

## 📚 Version of Software Used
validate 1.24.0

## 🩺 Test Data / Additional context
[crs009x.tab.gz](https://github.com/NASA-PDS/validate/files/6288046/crs009x.tab.gz)
[crs009x.xml.gz](https://github.com/NASA-PDS/validate/files/6288047/crs009x.xml.gz)
[crs009x_report.txt](https://github.com/NASA-PDS/validate/files/6288041/crs009x_report.txt)

##  🏞Screenshots
N/A

## 🖥 System Info
 - OS: Mac OSX 11.1
 - Browser: Safari 14.0.2
 - Version

---

** :unicorn: Applicable requirements**

**Comment by LevN0** [comment] 2021-04-13 07:35
Without commenting on what the validate tool should do,

>I have Table_Character files with long records. Carriage-Return Line-Feed pairs have been embedded within the records to facilitate display; but the original (long) record length has been retained in the label

This is a good way to make plain-ASCII data much more difficult to read for any non-specialized tool, for seemingly no benefit. Tools following standard will read it, but general tools shipping with the programming languages will choke. 

Embedded linebreaks facilitate display only if everyone has an agreed upon window size, otherwise they make the display worse.

**Comment by radiosci** [comment] 2021-04-13 14:07
Lev may be right about the behavior of non-PDS tools.  But, in my case, record_bytes clearly gives the desired record length and the last two characters are Carriage-Return Line-Feed, as required.  Does the fact that there are other control characters in the record override those specifications?  DDWG response to CCB-196 suggests not.
BTW, I would consider a WARNING from validate to be acceptable; but ERROR will keep me from submitting these files.

**Comment by tloubrieu-jpl** [comment] 2021-04-27 17:56
The counting of record need to be revised.

**Comment by radiosci** [comment] 2021-04-27 18:15
In Table_Character, the value of 'records' should be multiplied by the value of 'record_length' to obtain the value for 'file_size'.  This would be consistent with the calculation in Table_Binary. 
In Table_Character the value for 'records' is _not_ the count of CR-LF pairs (or 'LF' instances after CCB-264).  If that is how Validate behaves, then the comment from tloubrieu-jpl is correct.

**Comment by jordanpadams** [comment] 2021-04-27 18:58
@radiosci we are taking a look at this now, and will follow-up if we have any questions.

**Comment by qchaupds** [comment] 2021-04-28 23:35
We now have a DEV version of validate that can count correctly the number of expected records.
Fixing the issue is something we are working on.

Now a question for @radiosci : Is there a special reason why you commented out the field_format tag in the label?

```xml
                       <Field_Character>
                               <name>GM</name>
                               <field_number>2</field_number>
                               <field_location unit="byte">23</field_location>
                               <data_type>ASCII_Real</data_type>
                               <field_length unit="byte">26</field_length>
<!--                               <field_format>%26.18e</field_format>   -->
                               <unit>km**3/s**2/kg**2</unit>
                               <description>
                                     Gravitational constant for the body.  Set to zero if                 
                                     unknown or not available.
                               </description>
                         </Field_Character>
```

**Comment by qchaupds** [comment] 2021-04-28 23:37
For some reason, the previous comment does not show the commented out fields.  It shows blank line instead of the actual comment.

**Comment by radiosci** [comment] 2021-04-29 03:15
No reason; I may have been checking something else and forgot to remove the commenting markups.  Validate seems to work the same whether the 'field_format' line is commented or not.

**Comment by radiosci** [comment] 2021-04-29 03:24
Thanks, Jordan; I didn't mean to close the issue.  Shows my lack of experience with GitHub.

**Comment by jordanpadams** [comment] 2021-04-29 04:30
@radiosci no worries. It should be closed out soon.

**Comment by qchaupds** [comment] 2021-05-03 19:17
From the error message:

          "dataFile": "file:/home/qchau/sandbox/validate/src/test/resources/github325/crs009x.tab",
          "messages": [
            {
              "severity": "ERROR",
              "type": "error.table.record_length_mismatch",
              "table": 1,
              "record": 1,
              "message": "Record does not equal the defined record length (expected 246, got 82)."
            },

It looks like validate is reading one line (which is 81 characters plus the carriage return)

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate/src/test/resources/github325 124 % echo "                SUN     0.000000000000000000E+00  0.00000000E+00  0.00000000E+00" | wc -c
81

There may be some flaw logic in making assumption that the record ends at the carriage returns instead of reading until it had read the expected 246 characters.

This issue is a little more complicated to fix.  Stay tune.

**Comment by radiosci** [comment] 2021-05-03 20:34
>There may be some flaw logic in making assumption that the record ends at the carriage returns instead of reading until it had read the expected 246 characters.

  agreed.

**Comment by qchaupds** [comment] 2021-05-04 17:42
Issue #335 will be working on together with this issue since fixing this issue causing a null pointer for other kinds of label.

Having said that, the good news is we do have a fix for this issue #325 but will do more testing as it is breaking other codes.  Will post more test results when code is more stable.

**Comment by tloubrieu-jpl** [comment] 2021-05-04 18:01
Seen in stand up: The `record_length` or `maximum_record_length` takes precedence in determining a record versus using the record delimiters first when parsing.

**Comment by qchaupds** [comment] 2021-05-04 18:05
Actually, @jordanpadams , please reopen this since the regression test is failing at the moment.

**Comment by qchaupds** [comment] 2021-05-04 23:39
We have good results from DEV so far:

validate -R pds4.label --skip-context-validation -r report_github325_label_valid.json -s json -t src/test/resources/github325/crs009x.xml >

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 128 % egrep "status|label" report_github325_label_valid.json
    "ruleType": "pds4.label",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github325/crs009x.xml",

The label specifies how many records:

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 129 % egrep records /home/qchau/sandbox/validate/src/test/resources/github325/crs009x.xml
                   <records>2</records>

and validate confirms the record count:

[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule - validateTableRecordWise:dataFile,recordSize file:/home/qchau/sandbox/validate/src/test/resources/github325/crs009x.tab,2

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 132 %  egrep -i tablerecord t1
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule - validateTableRecordWise:table instanceof TableCharacter
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule - validateTableRecordWise:tableIndex,spotCheckData,keepQuotationsFlag 1,-1,true
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule - validateTableRecordWise:**dataFile,recordSize file:/home/qchau/sandbox/validate/src/test/resources/github325/crs009x.tab,2**
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule - validateTableRecordWise: recordNumber 1
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule - validateTableRecordWise: recordNumber 2
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule - validateTableRecordWise:DONE_VALIDATING

**Comment by radiosci** [comment] 2021-05-05 00:02
Thanks for your work on this.  I'm sorry about the unexpected work, but I think you are on the right track.  IMHO, the values for 'record_length' and 'records' should take precedence over discovery of delimiters within records.

**Closed as completed** 2021-05-07 23:10 UTC
Labels: bug, B12.0, s.medium
