### ISSUE TITLE
Incorrect errors with heterogeneous root tags and prologs

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#208] opened 2020-04-03 20:40 UTC
**See also parent ticket #188 for additional details**

---

Fixing this might be too costly performance-wise. Your call.

Validating the attached directory produces errors when loading the schema of some files. However, validating those files individually works.
% validate -e "*.xml" -t val149
PDS Validate Tool Report
Configuration:
   Version                       1.22.1
   Date                          2020-04-03T18:30:12Z\
Parameters:
   Targets                       [file:/Users/rchen/Desktop/test/testPrep/val149/]
[snip...]
  PASS: file:/Users/rchen/Desktop/test/testPrep/val149/val149bin2anc.xml
        1 product validation(s) completed
  FAIL: file:/Users/rchen/Desktop/test/testPrep/val149/val149del2anc.xml
    Begin Schema: https://pds.nasa.gov/pds4/rings/v1/PDS4_RINGS_1D00_1900.xsd
      ERROR  [error.label.schema]   line 1059, 78: src-resolve: Cannot resolve the name 'pds:Units_of_Gmass' to a(n) 'type definition' component.
      ERROR  [error.label.schema]   line 1059, 78: src-resolve: Cannot resolve the name 'pds:Units_of_Gmass' to a(n) 'simpleType definition' component.
      ERROR  [error.label.schema]   line 167, 74: src-resolve: Cannot resolve the name 'pds:local_identifier' to a(n) 'element declaration' component.
[snip...]
% validate -t val149/val149del2anc.xml
PDS Validate Tool Report
Configuration:
   Version                       1.22.1
   Date                          2020-04-03T20:35:48Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/test/testPrep/val149/val149del2anc.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/test/testPrep/val149/val149del2anc.xml
        1 product validation(s) completed

The root tags and prologs of the labels are very different. Maybe what's happening is that when validating a directory, validate uses the first label's definition of namespaces and then uses it on the rest, so definitions may have changed or not have existed yet.
[val149.zip](https://github.com/NASA-PDS-Incubator/validate/files/4429819/val149.zip)

**Comment by jordanpadams** [comment] 2020-04-07 01:06
Related to if not the same as #188

**Comment by rchenatjpl** [comment] 2020-04-29 03:57
gawdblessit A few labels pointed to an incorrect data file. Fixed in the attached. If you want to avoid the bug described in issue #208, do:
% validate -t val217/a*xml ; validate -t val217/b*xml ; validate -t val217/d*xml
instead of
% validate -t val217

[val217.tar.gz](https://github.com/NASA-PDS-Incubator/validate/files/4549728/val217.tar.gz)

**Comment by jordanpadams** [comment] 2020-05-22 02:44
Duplicate of #188

**Closed as completed by jordanpadams** 2020-05-22 02:44 UTC
Labels: bug, duplicate
